### ISSUE TITLE
Can't resolve http://checkip.dyndns.com

### ISSUE THREAD

**Issue by RcrdBrt** [niklata/ndyndns#3]
I have 2 installations of ndyndns, both from archlinux (1 on ARM and 1 on x86_64). The latter is working perfectly fine while the ARM installation can't resolve correctly the checkip.dyndns.com and it keep saying so since I installed it for the last 2 days. During this time it never updated the IP to the right one on namecheap.com.

![screenshot from 2016-05-01 10-56-16](https://cloud.githubusercontent.com/assets/1354394/14940958/a9cbfd50-0f8b-11e6-9ed7-3c6fc9cec335.png)

**Comment by niklata** [comment]
The most likely problem is glibc on arm not being able to load some dependent library required for its DNS stub resolver to function because ndyndns is running in a chroot.  "Could not resolve host" means that DNS lookups on checkip.dyndns.com aren't succeeding.

ndyndns works around this on x86 and x86_64 by querying gethostbyname("fail.invalid"); before chrooting and dropping privs from root.  This method forces the dependent nss-related glibc libraries to load.  I would naively expect this trick to work on arm, too, but maybe it doesn't for some reason.

Maybe try disabling chroot (-x on the command line) and see if that fixes the problem?  Another useful thing would be the output of ldd on the ndyndns executable, so we could see what libraries it depends on.

If disabling chroot fixes the issue, that probably will be the best solution.

I don't have an armv7l machine, so it'll be difficult for me to hunt down this problem like I usually would.

**Comment by RcrdBrt** [comment]
this is the output from `ldd $(which ndyndns)`.

![screenshot from 2016-05-01 17-49-26](https://cloud.githubusercontent.com/assets/1354394/14942702/7e20c958-0fc5-11e6-8460-dabf51d1c759.png)

Adding the -x param to the systemd service fails because ndyndns still requires a chroot path with -c. Launching with the -x it says `FATAL - No chroot path specified.  Refusing to run.`

**Comment by niklata** [comment]
Try again after removing the -c flag.  -x and -c together don't really make sense and ndyndns is probably deliberately failing because of that.  -x is just an override to say "I'm ok if ndyndns runs without a chroot".

Those are a _lot_ more libraries than on my x86-64 machine; I strongly suspect that running without chroot should fix the problem.

**Comment by RcrdBrt** [comment]
If I insert the -x flag on the command-line, ndyndns fails saying it needs a -c flag + a chroot path. Sorry if I wasn't clear earlier. (the IP showed is a random placeholder IP)
![screenshot from 2016-05-01 18-08-30](https://cloud.githubusercontent.com/assets/1354394/14942797/b8bf6a86-0fc7-11e6-8969-51bce927b3e5.png)

**Comment by niklata** [comment]
This looks to be a bug in the older version of ndyndns that's packaged in arch (the legacy-dyn branch)

This patch would fix that problem with -x not working properly:

--- ndyndns.c.orig      2016-05-01 12:13:57.883557593 -0400
+++ ndyndns.c   2016-05-01 12:14:04.228636311 -0400
@@ -397,9 +397,6 @@ int main(int argc, char*\* argv)
     umask(077);
     fix_signals();
-    if (!chroot_exists())

## \-        suicide("FATAL - No chroot path specified.  Refusing to run.");

```
 /* Note that failure cases are handled by called fns. */
 imprison(get_chroot());
 drop_root(cfg_uid, cfg_gid);
```

**Comment by niklata** [comment]
Bleh, it was mangled by the rich text formatting; I'll push a commit to that branch that should fix it.

**Comment by RcrdBrt** [comment]
![screenshot from 2016-05-01 18-22-46](https://cloud.githubusercontent.com/assets/1354394/14942863/c29c8276-0fc9-11e6-8481-8c3709f8219d.png)
I have the code you posted above in the sources I compiled to get ndyndns running. The codebase is updated to v2.3.

**Comment by niklata** [comment]
Try deleting out the two
if (!chroot_exists())
suicide("FATAL - No chroot path specified. Refusing to run.");

lines and compiling.

**Comment by niklata** [comment]
Looking at that I wouldn't be very surprised if another solution would be to move the two lines that begin with curl_global_init() and use_ssl = ... lines above imprison().  That might allow the chroot to work properly.

**Comment by RcrdBrt** [comment]
I moved the 2 lines above the imprison function() but it still wasn't able to resolve the URL. Then I removed the `suicide if the chroot wasn't defined` and it updated my IP sucessfully to the namecheap dynamic DNS entry. Thank you for the support. By the way why adding the chroot thing if it isn't necessary? 
I'd say you can safely add in your README that ndyndns is working fine on ARMv7l (raspberry pi) devices if the chroot is disabled.

**Comment by niklata** [comment]
Thanks for your patience and I'm sorry for writing the bug that broke -x to begin with!

It's too bad that moving up the ssl initialization didn't make things work with chroot, but thank you for letting me know that isn't a valid fix.

chroot is just an extra security feature for "defense in depth".  It makes ndyndns run within an almost-empty directory that looks like the root directory to ndyndns.  That way it's very difficult or impossible for the ndyndns process to read or write to files that aren't already open within the ndyndns process even if it is somehow compromised by a security issue.

Running without chroot just means that if someone managed to find a severe code-execution bug in ndyndns, they'd be able to read files that the ndyndns user has permissions to read anywhere on the normal filesystem hierarchy.

I'll add a note that ndyndns works on ARM7vl / Raspberry Pi to the README, and thank you for letting me know that everything seems to be working now.

**Comment by RcrdBrt** [comment]
Understood. Thanks to you again for the support & explanation!
