### ISSUE TITLE
ndyndns AUR package build failure.

### ISSUE THREAD

**Issue by apottere** [niklata/ndyndns#5]
I'm using `yay` to update the AUR package for `ndyndns`, and I'm getting the following error:
```
dns_helpers.c: In function 'update_ip_curl_errcheck':
dns_helpers.c:177:9: error: duplicate case value
  177 |         case CURLE_SSL_CACERT:
      |         ^~~~
dns_helpers.c:172:9: note: previously used here
  172 |         case CURLE_SSL_PEER_CERTIFICATE:
      |         ^~~~
make: *** [<builtin>: dns_helpers.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

I tried building `ndyndns` from source but I can't get that working either.

**Comment by niklata** [comment]
I've pushed an untested commit to both branches of ndyndns that should fix that error.  Let me know how it goes for you.

I don't know whether the source of the issue is a change to CURL or stricter compiler behavior; the CURLE_SSL_CACERT and CURLE_SSL_PEER_CERTIFICATE macros map to the same value and map to the same destination in the associated switch statement, so there is no semantic error, so I've just made the simple change of removing the CURLE_SSL_CACERT case.

**Comment by apottere** [comment]
@niklata I'm not able to build `ndyndns` on arch from master because of this error, not sure if there's another library I need to install first: 
```
util.c:34:10: fatal error: nk/log.h: No such file or directory
   34 | #include "nk/log.h"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [<builtin>: util.o] Error 1
```

However, it looks like the AUR pkgbuild is using `v2.3`, so I cherry-picked your fix commit onto that tag and it built and installed just fine.

**Comment by niklata** [comment]
Great, I've tagged a new 2.3.1 release that includes the fix and points to the current legacy-dyn branch.

The build error you were getting when trying to build master (3.x) comes from needing ncmlib installed or symlinked into the ndyndns build directory.  The legacy-dyn branch contains a snapshot of ncmlib, so it isn't required in that case.  But it's probably best to just use legacy-dyn as long as it's working well.

**Comment by apottere** [comment]
Thanks for getting that done!
